baseurl = "aaaaaaaaaaaaaaaaa"
title = "Firo Notes"
languageCode = "en-us"
disqusShortname = "firoyang"
copyright = "Copyright (c) 2015, Nanshu Wang; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Firo Yang"

[indexes]
    tag = "tags"
    topic = "topics"

